# Generated by Django 3.0.5 on 2021-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('time', models.DateTimeField(default='')),
            ],
        ),
    ]
